// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const game_player: { "backLabel": string; "gameInfoTitle": string; "controlsTitle": string; "notFoundMessage": string; "controls": Array<{ "id": string; "key": string; "action": string }> };
  export const home: { "heroTitle": string; "heroSubtitle": string; "libraryTitle": string; "stats": Array<{ "id": string; "label": string; "color": string }> };
}
